-- BACKUP COMPLETO SPARK COMEX
-- Data: 2025-07-06T04:06:01.229Z
-- Origem: Neon Database
-- Destino: SQLite Migration
-- 
-- INSTRUÇÕES DE RESTAURAÇÃO:
-- 1. Execute este arquivo em qualquer banco PostgreSQL/SQLite
-- 2. Todos os dados serão restaurados
-- 3. Mantenha este arquivo como backup de segurança
--
-- TABELAS INCLUÍDAS: users, credit_applications, imports, suppliers, admin_fees, credit_usage, payment_schedules, payments, import_documents, import_payments, import_products, import_timeline, notifications, api_configurations, cnpj_analyses, consultamais_analysis, sessions

SET client_encoding = 'UTF8';
-- ERRO ao exportar users: syntax error at or near "$1"
-- ERRO ao exportar credit_applications: syntax error at or near "$1"
-- ERRO ao exportar imports: syntax error at or near "$1"
-- ERRO ao exportar suppliers: syntax error at or near "$1"
-- ERRO ao exportar admin_fees: syntax error at or near "$1"
-- ERRO ao exportar credit_usage: syntax error at or near "$1"
-- ERRO ao exportar payment_schedules: syntax error at or near "$1"
-- ERRO ao exportar payments: syntax error at or near "$1"
-- ERRO ao exportar import_documents: syntax error at or near "$1"
-- ERRO ao exportar import_payments: syntax error at or near "$1"
-- ERRO ao exportar import_products: syntax error at or near "$1"
-- ERRO ao exportar import_timeline: syntax error at or near "$1"
-- ERRO ao exportar notifications: syntax error at or near "$1"
-- ERRO ao exportar api_configurations: syntax error at or near "$1"
-- ERRO ao exportar cnpj_analyses: syntax error at or near "$1"
-- ERRO ao exportar consultamais_analysis: syntax error at or near "$1"
-- ERRO ao exportar sessions: syntax error at or near "$1"

-- FIM DO BACKUP - 2025-07-06T04:06:02.754Z
